import {authenticatedUser,unauthorized} from "@/lib/access";
import {database,initialize} from "@/lib/store";
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"private, no-store"}});
const tables={entity:"entities",connection:"connections",article:"articles"} as const;
function targetKind(value:unknown):value is keyof typeof tables{return value==="entity"||value==="connection"||value==="article";}
export async function GET(request:Request){const owner=authenticatedUser(request);if(!owner)return unauthorized();const p=new URL(request.url).searchParams,kind=p.get("kind"),id=p.get("id");if(!targetKind(kind)||!id)return json({error:"Choose an entity, connection, or article for these notes."},400);try{await initialize(owner);const result=await database().prepare("SELECT id,target_kind AS targetKind,target_id AS targetId,body,created,updated FROM notes WHERE owner_id=? AND target_kind=? AND target_id=? ORDER BY created DESC,id DESC LIMIT 500").bind(owner,kind,id).all();return json({notes:result.results});}catch(e){console.error("Notes read failed",e);return json({error:"Your notes are temporarily unavailable. Please retry."},503);}}
async function mutate(request:Request,method:"POST"|"PATCH"|"DELETE"){const owner=authenticatedUser(request);if(!owner)return unauthorized();const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return json({error:"Request origin is not allowed."},403);if(!request.headers.get("content-type")?.includes("application/json"))return json({error:"JSON is required."},415);let b:Record<string,unknown>;try{const raw=await request.text();if(new TextEncoder().encode(raw).length>16384)return json({error:"Request is too large. Keep it within 16 KB."},413);const parsed:unknown=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error();b=parsed as Record<string,unknown>;}catch{return json({error:"Invalid request."},400);}const body=typeof b.body==="string"?b.body.trim():"";if(method!=="DELETE"&&(!body||body.length>8000))return json({error:body?"Keep your note within 8000 characters.":"Write something before saving."},400);try{await initialize(owner);const db=database();if(method==="POST"){if(!targetKind(b.kind)||typeof b.id!=="string"||!b.id)return json({error:"Choose an entity, connection, or article for this note."},400);const exists=await db.prepare("SELECT id FROM "+tables[b.kind]+" WHERE owner_id=? AND id=?").bind(owner,b.id).first();if(!exists)return json({error:"The note target was not found."},404);const id=crypto.randomUUID(),now=new Date().toISOString();const result=await db.prepare("INSERT INTO notes (owner_id,id,target_kind,target_id,body,created,updated) SELECT ?,?,?,?,?,?,? WHERE (SELECT count(*) FROM notes WHERE owner_id=? AND target_kind=? AND target_id=?)<500").bind(owner,id,b.kind,b.id,body,now,now,owner,b.kind,b.id).run();return result.meta.changes?json({ok:true,id},201):json({error:"This target already has 500 notes."},400);}if(typeof b.noteId!=="string"||!b.noteId)return json({error:"Choose the note you want to change."},400);const existing=await db.prepare("SELECT updated FROM notes WHERE owner_id=? AND id=?").bind(owner,b.noteId).first<{updated:string}>();if(!existing)return json({error:"Note not found."},404);if(method==="DELETE")await db.prepare("DELETE FROM notes WHERE owner_id=? AND id=?").bind(owner,b.noteId).run();else{const updated=new Date(Math.max(Date.now(),Date.parse(existing.updated)+1)).toISOString();await db.prepare("UPDATE notes SET body=?,updated=? WHERE owner_id=? AND id=?").bind(body,updated,owner,b.noteId).run();}return json({ok:true});}catch(e){console.error("Notes update failed",e);return json({error:"Your note could not be saved. Please retry."},503);}}
export const POST=(request:Request)=>mutate(request,"POST");
export const PATCH=(request:Request)=>mutate(request,"PATCH");
export const DELETE=(request:Request)=>mutate(request,"DELETE");
