"use client";
/* eslint-disable next/no-img-element */
import {useEffect,useState,type CSSProperties} from "react";
import {ArrowUpRight,Check,ExternalLink,Lightbulb,Network,Plus,Rss,Users} from "lucide-react";
import {EntityFields} from "@/components/entity-fields";
import {FeedField} from "@/components/feed-field";
import {NotesPanel} from "@/components/notes-panel";
import type {Article,Briefing,Connection,Entity} from "@/lib/intelligence";
type Props={entities:Entity[];connections:Connection[];briefing:Briefing|null;selected:Entity|null;edge:Connection|null;loaded:boolean;onFollow:(entity:Entity)=>void;onEdge:(connection:Connection)=>void;onEntity:(entity:Entity)=>void;onFeed:(entity:Entity,feedUrl:string)=>Promise<void>;onEntitySave:(entity:Entity,change:{kind?:string;image?:string})=>Promise<void>};
type ArticleResult=Article&{summary?:string;firstSeen?:string};
function Badge({entity}:{entity:Entity}){return <span className="entity-avatar" style={{"--entity-color":entity.color} as CSSProperties}>{entity.image?<img src={entity.image} alt=""/>:entity.initials}</span>}
export function Inspector({entities,connections,briefing,selected,edge,loaded,onFollow,onEdge,onEntity,onFeed,onEntitySave}:Props){
  const[items,setItems]=useState<ArticleResult[]>([]),[page,setPage]=useState(0);
  useEffect(()=>{if(!selected)return;const controller=new AbortController();void fetch("/api/workspace?articles="+encodeURIComponent(selected.id)+"&limit=100",{signal:controller.signal}).then(async response=>{const data=await response.json() as {articles?:ArticleResult[]};if(response.ok)setItems(data.articles??[])}).catch(()=>{});return()=>controller.abort()},[selected]);
  if(edge){const from=entities.find(entity=>entity.id===edge.from),to=entities.find(entity=>entity.id===edge.to);return <aside className="inspector-content"><header><span className="eyebrow">CONNECTION</span><h2>{from?.name} → {to?.name}</h2><p>{edge.label}</p></header><section><h3>Evidence</h3><span className={"evidence-status "+(edge.status==="Hypothesis"?"hypothesis":"")}>{edge.status}</span><p>{edge.evidence}</p><p className="muted">Source date: {edge.date||"Not specified"}</p><a className="source-link" href={edge.url} target="_blank" rel="noreferrer">Read source <ExternalLink size={14}/></a></section><NotesPanel kind="connection" id={edge.id}/><section><h3>Endpoints</h3>{[from,to].filter(Boolean).map(entity=><button key={entity!.id} className="inspector-endpoint" onClick={()=>onEntity(entity!)}><Badge entity={entity!}/><span>{entity!.name}<small>{entity!.kind}</small></span></button>)}</section></aside>}
  if(!selected){const market=entities.filter(entity=>entity.profile),followed=entities.filter(entity=>entity.followed);return <aside className="inspector-content inspector-empty"><header><span className="eyebrow">AI MARKET</span><h2>Company analysis</h2><p>Select a company in the market explorer or relationship map to inspect its products, customers, revenue model, and entry opportunities.</p></header><div className="inspector-totals"><span><Users size={16}/><strong>{market.length}</strong> companies</span><span><Network size={16}/><strong>{new Set(market.map(entity=>entity.profile!.vertical)).size}</strong> market areas</span><span><Rss size={16}/><strong>{followed.length}</strong> monitored</span></div></aside>}
  const related=connections.filter(connection=>connection.from===selected.id||connection.to===selected.id),pageSize=8,pages=Math.max(1,Math.ceil(items.length/pageSize)),shown=items.slice(Math.min(page,pages-1)*pageSize,Math.min(page,pages-1)*pageSize+pageSize),p=selected.profile;
  return <aside className="inspector-content"><header><Badge entity={selected}/><span className="eyebrow">{selected.kind}</span><h2>{selected.name}</h2><p>{selected.description}</p><button className={selected.followed?"following-button":"follow-button"} disabled={!loaded} onClick={()=>onFollow(selected)}>{selected.followed?<Check size={14}/>:<Plus size={14}/>} {selected.followed?"Monitoring":"Monitor"}</button>{selected.source&&<a className="source-link" href={selected.source} target="_blank" rel="noreferrer">Official site <ExternalLink size={14}/></a>}</header>
    {p&&<section className="market-profile"><div className="profile-score"><span>Opportunity score</span><strong>{p.opportunityScore}</strong><i><b style={{width:p.opportunityScore+"%"}}/></i></div><div className="profile-grid"><span>Market<strong>{p.vertical}</strong></span><span>Stage<strong>{p.stage}</strong></span><span>Headquarters<strong>{p.hq}</strong></span><span>Founded<strong>{p.founded}</strong></span></div><h3>Core products</h3><ul>{p.products.map(product=><li key={product}>{product}</li>)}</ul><h3>Target customers</h3><p>{p.targetCustomer}</p><h3>Revenue model</h3><p>{p.revenueModel}</p><div className="profile-opportunity"><Lightbulb size={15}/><div><strong>Entry opportunity</strong><p>{p.opportunity}</p></div></div><small className="profile-verified">Public sources reviewed {p.lastVerified}</small></section>}
    <section><h3>Recent intelligence</h3>{shown.map(article=><a className="inspector-article" key={article.id} href={article.url} target="_blank" rel="noreferrer"><span>{article.source} · {new Date(article.published).toLocaleDateString()}</span><strong>{article.title}</strong>{article.summary&&<p>{article.summary}</p>}</a>)}{!shown.length&&<p className="muted">No saved articles mention this company yet.</p>}{pages>1&&<div className="inspector-pages"><button disabled={page===0} onClick={()=>setPage(value=>Math.max(0,value-1))}>Previous</button><span>{Math.min(page,pages-1)+1} / {pages}</span><button disabled={page>=pages-1} onClick={()=>setPage(value=>Math.min(pages-1,value+1))}>Next</button></div>}</section>
    <NotesPanel kind="entity" id={selected.id}/><section><h3>Relationships</h3>{related.map(connection=>{const other=entities.find(entity=>entity.id===(connection.from===selected.id?connection.to:connection.from));return <button className="inspector-connection" key={connection.id} onClick={()=>onEdge(connection)}><span>{other?.name}</span><small>{connection.label} · {connection.status}</small><ArrowUpRight size={14}/></button>})}{!related.length&&<p className="muted">No relationships recorded yet.</p>}</section><EntityFields key={selected.kind+"|"+(selected.image??"")} entity={selected} onSave={onEntitySave}/><FeedField key={selected.feedUrl??""} entity={selected} onSave={onFeed}/>
  </aside>
}
