"use client";
import {useMemo,useState,type CSSProperties} from "react";
import {ArrowUpRight,Building2,Filter,Lightbulb,MapPin,Search,ShieldCheck,Sparkles,Users2} from "lucide-react";
import type {Entity} from "@/lib/intelligence";
type Props={entities:Entity[];query:string;onSelect:(entity:Entity)=>void};
type Sort="opportunity"|"name"|"newest";
const ALL="All";
export function MarketDashboard({entities,query,onSelect}:Props){
  const market=useMemo(()=>entities.filter(entity=>entity.profile),[entities]);
  const layers=useMemo(()=>[...new Set(market.map(entity=>entity.profile!.layer))].sort(),[market]);
  const verticals=useMemo(()=>[...new Set(market.map(entity=>entity.profile!.vertical))].sort(),[market]);
  const[layer,setLayer]=useState(ALL),[vertical,setVertical]=useState(ALL),[startupsOnly,setStartupsOnly]=useState(true),[sort,setSort]=useState<Sort>("opportunity");
  const needle=query.trim().toLowerCase();
  const shown=useMemo(()=>market.filter(entity=>{const p=entity.profile!,haystack=[entity.name,p.layer,p.vertical,p.targetCustomer,p.revenueModel,p.products.join(" "),p.tags.join(" ")].join(" ").toLowerCase();return(!needle||haystack.includes(needle))&&(layer===ALL||p.layer===layer)&&(vertical===ALL||p.vertical===vertical)&&(!startupsOnly||p.startup)}).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="newest"?b.profile!.founded-a.profile!.founded:b.profile!.opportunityScore-a.profile!.opportunityScore),[market,needle,layer,vertical,startupsOnly,sort]);
  const startupCount=market.filter(entity=>entity.profile!.startup).length,highOpportunity=market.filter(entity=>entity.profile!.opportunityScore>=65).length,topVertical=[...verticals].map(name=>({name,count:market.filter(entity=>entity.profile!.vertical===name).length})).sort((a,b)=>b.count-a.count)[0];
  return <section className="market-dashboard">
    <header className="market-heading"><div><span className="market-kicker"><Sparkles size={13}/> AI MARKET INTELLIGENCE</span><h1>Opportunity Explorer</h1><p>Compare products, customers, and revenue models on one consistent framework to find less crowded entry points.</p></div><div className="verified-chip"><ShieldCheck size={15}/><span>Public-source research</span><strong>Sep 9, 2026</strong></div></header>
    <div className="market-stats"><article><Building2/><span>Companies analyzed</span><strong>{market.length}</strong><small>Global AI companies</small></article><article><Sparkles/><span>Startups</span><strong>{startupCount}</strong><small>Early to late stage</small></article><article><Lightbulb/><span>Opportunity score 65+</span><strong>{highOpportunity}</strong><small>Higher-potential spaces</small></article><article><Users2/><span>Most competitive area</span><strong>{topVertical?.count??0}</strong><small>{topVertical?.name??"—"}</small></article></div>
    <div className="market-controls"><div className="filter-block"><span><Filter size={13}/> Technology layer</span><div className="market-pills"><button className={layer===ALL?"active":""} onClick={()=>setLayer(ALL)}>All <b>{market.length}</b></button>{layers.map(name=><button key={name} className={layer===name?"active":""} onClick={()=>setLayer(name)}>{name} <b>{market.filter(entity=>entity.profile!.layer===name).length}</b></button>)}</div></div><div className="filter-row"><label>Market<select value={vertical} onChange={event=>setVertical(event.target.value)}><option>{ALL}</option>{verticals.map(name=><option key={name}>{name}</option>)}</select></label><label>Sort by<select value={sort} onChange={event=>setSort(event.target.value as Sort)}><option value="opportunity">Highest opportunity</option><option value="newest">Newest companies</option><option value="name">Company name</option></select></label><button className={startupsOnly?"startup-toggle active":"startup-toggle"} onClick={()=>setStartupsOnly(value=>!value)} aria-pressed={startupsOnly}><span/> Startups only</button><div className="result-count">{shown.length} results</div></div></div>
    <div className="company-grid">{shown.map(entity=>{const p=entity.profile!;return <article key={entity.id} className="company-card" onClick={()=>onSelect(entity)} tabIndex={0} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onSelect(entity)}}}><div className="company-card-top"><span className="company-mark" style={{"--entity-color":entity.color} as CSSProperties}>{entity.initials}</span><div><h2>{entity.name}</h2><p><MapPin size={11}/>{p.hq} · {p.founded}</p></div><span className={"stage-badge "+(p.startup?"":"incumbent")}>{p.stage}</span></div><div className="company-tags"><span>{p.layer}</span><span>{p.vertical}</span>{p.tags.slice(0,2).map(tag=><span key={tag}>#{tag}</span>)}</div><div className="company-section"><small>Core products</small><strong>{p.products.slice(0,2).join(" · ")}</strong></div><div className="company-section"><small>Target customers</small><p>{p.targetCustomer}</p></div><div className="company-section revenue"><small>Revenue model</small><p>{p.revenueModel}</p></div><div className="opportunity-row"><div><span>Opportunity</span><strong>{p.opportunityScore}</strong></div><div className="score-track"><i style={{width:p.opportunityScore+"%"}}/></div><button onClick={event=>{event.stopPropagation();onSelect(entity)}}>View analysis <ArrowUpRight size={13}/></button></div></article>})}{!shown.length&&<div className="market-empty"><Search size={22}/><strong>No companies match these filters.</strong><span>Try a different search or filter.</span></div>}</div>
    <footer className="market-method"><ShieldCheck size={14}/><span>Revenue models are normalized from public pricing and product pages. The opportunity score combines competitive intensity, buyer urgency, workflow clarity, and defensibility. It is an exploration aid, not investment advice.</span></footer>
  </section>
}
