"use client";
import {useEffect,useState} from "react";
type Note={id:string;body:string;created:string;updated:string};
export function NotesPanel({kind,id}:{kind:"entity"|"connection"|"article";id:string}){
  const [notes,setNotes]=useState<Note[]>([]),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();void fetch("/api/notes?kind="+kind+"&id="+encodeURIComponent(id),{signal:controller.signal}).then(async r=>{const data=await r.json() as {notes?:Note[];error?:string};if(!r.ok)throw new Error(data.error??"Your notes could not be loaded.");setNotes(data.notes??[]);setLoading(false);}).catch((e:unknown)=>{if(!controller.signal.aborted){setError(e instanceof Error?e.message:"Your notes could not be loaded.");setLoading(false);}});return()=>controller.abort();},[kind,id]);
  async function save(event:{preventDefault():void}){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/notes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id,body})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??"Your note could not be saved.");setBody("");const list=await fetch("/api/notes?kind="+kind+"&id="+encodeURIComponent(id));const data=await list.json() as {notes?:Note[];error?:string};if(!list.ok)throw new Error(data.error??"Your notes could not be loaded.");setNotes(data.notes??[]);}catch(e){setError(e instanceof Error?e.message:"Your note could not be saved.");}finally{setBusy(false);}}
  return <section className="notes-panel" aria-label="Personal notes"><h3>Your notes</h3><form className="desk-form" onSubmit={event=>void save(event)}><label>New note<textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={8000} required placeholder="What stands out to you?"/></label><button type="submit" className="primary-button" disabled={busy||!body.trim()}>{busy?"Saving…":"Save note"}</button></form>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p className="muted">Loading notes…</p>:notes.length?notes.map(note=><article className="personal-note" key={note.id}><time dateTime={note.created}>{new Date(note.created).toLocaleString()}</time><p>{note.body}</p></article>):<p className="muted">No notes yet.</p>}</section>;
}

