import {entityMatches,safeWebUrl,type Entity,type Source,type Article} from "./intelligence";
// These are fixed public feeds. Entity names and user watchlists never leave the app.
export function newsSources():Source[]{return [
{id:"openai",name:"OpenAI · official",url:"https://openai.com/news/",feed:"https://openai.com/news/rss.xml"},
{id:"fbi",name:"FBI · official",url:"https://www.fbi.gov/news/press-releases",feed:"https://www.fbi.gov/feeds/national-press-releases/rss.xml"},
{id:"world",name:"World · Google News",url:"https://news.google.com/",feed:"https://news.google.com/rss/headlines/section/topic/WORLD?hl=en-US&gl=US&ceid=US:en"},
{id:"us",name:"US news · Google News",url:"https://news.google.com/",feed:"https://news.google.com/rss/headlines/section/topic/NATION?hl=en-US&gl=US&ceid=US:en"},
{id:"technology",name:"Technology · Google News",url:"https://news.google.com/",feed:"https://news.google.com/rss/headlines/section/topic/TECHNOLOGY?hl=en-US&gl=US&ceid=US:en"},
{id:"business",name:"Business · Google News",url:"https://news.google.com/",feed:"https://news.google.com/rss/headlines/section/topic/BUSINESS?hl=en-US&gl=US&ceid=US:en"}
];}
export function decodeText(input:string){return input.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]*>/g,"").replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(_,entity)=>{const map:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" "};if(entity[0]!=="#")return map[entity.toLowerCase()]??"";const n=entity[1].toLowerCase()==="x"?parseInt(entity.slice(2),16):parseInt(entity.slice(1),10);return Number.isFinite(n)&&n>0&&n<=0x10ffff?String.fromCodePoint(n):"";}).trim();}
function tag(block:string,name:string){const match=block.match(new RegExp("<"+name+"(?:\\s[^>]*)?>([\\s\\S]*?)</"+name+">","i"));return match?decodeText(match[1]):"";}
export function parseRss(xml:string,source:Source,entities:Entity[],now=Date.now()):Article[]{if(!/<rss\b|<rdf:RDF\b/i.test(xml))throw new Error("Feed was not RSS");const blocks=xml.match(/<item(?:\s[^>]*)?>[\s\S]*?<\/item>/gi)??[];const articles:Article[]=[];for(const block of blocks.slice(0,150)){const title=tag(block,"title"),url=safeWebUrl(tag(block,"link")),date=Date.parse(tag(block,"pubDate")||tag(block,"dc:date"));if(!title||!url||!Number.isFinite(date)||date>now+3600000||date<now-7*86400000)continue;const publisher=tag(block,"source")||source.name;const entityIds=entities.filter(e=>entityMatches(title+" "+publisher,e)).map(e=>e.id);if(source.id==="openai"&&!entityIds.includes("openai"))entityIds.push("openai");if(source.id==="fbi"&&!entityIds.includes("fbi"))entityIds.push("fbi");articles.push({id:url,title:title.slice(0,450),url,source:publisher,published:new Date(date).toISOString(),entities:entityIds});}return articles;}
export async function fetchFeed(source:Source,entities:Entity[]){const checked=new Date().toISOString();try{const response=await fetch(source.feed,{headers:{"Accept":"application/rss+xml, application/xml, text/xml","User-Agent":"BigBrotherIntelligence/1.0"},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error("Feed unavailable");if(Number(response.headers.get("content-length"))>1500000)throw new Error("Feed too large");const reader=response.body?.getReader();if(!reader)throw new Error("Feed empty");let size=0,xml="";const decoder=new TextDecoder();for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>1500000){await reader.cancel();throw new Error("Feed too large")}xml+=decoder.decode(value,{stream:true});}xml+=decoder.decode();const articles=parseRss(xml,source,entities);return {source:{...source,status:"ok",count:articles.length,checked},articles};}catch{return {source:{...source,status:"error",count:0,checked},articles:[] as Article[]};}}

