import {forceCenter,forceCollide,forceLink,forceManyBody,forceSimulation,type SimulationNodeDatum} from "d3-force";
import type {Connection,Entity} from "./intelligence";
export type GraphLayout=Record<string,[number,number]>;
export type GroupDimension="vertical"|"hq"|"layer"|"stage";
type LayoutNode=SimulationNodeDatum&{id:string};
type LayoutLink={source:string|LayoutNode;target:string|LayoutNode};
export function seedLayout(entities:Entity[],connections:Connection[]):GraphLayout{const nodes:LayoutNode[]=entities.map(entity=>({id:entity.id}));const ids=new Set(nodes.map(node=>node.id));const links:LayoutLink[]=connections.filter(connection=>ids.has(connection.from)&&ids.has(connection.to)).map(connection=>({source:connection.from,target:connection.to}));forceSimulation(nodes).force("link",forceLink<LayoutNode,LayoutLink>(links).id(node=>node.id).distance(180)).force("charge",forceManyBody<LayoutNode>().strength(-800)).force("center",forceCenter(0,0)).force("collide",forceCollide(90)).stop().tick(400);return Object.fromEntries(nodes.map(node=>[node.id,[Math.round(node.x??0),Math.round(node.y??0)]]));}
export function groupValue(entity:Entity,dimension:GroupDimension){const p=entity.profile;if(!p)return "Other";if(dimension==="hq")return p.hq.split(",").at(-1)?.trim()||p.hq;if(dimension==="layer")return p.layer;if(dimension==="stage")return p.stage;return p.vertical;}
export function groupLayout(entities:Entity[],dimension:GroupDimension):GraphLayout{const grouped=new Map<string,Entity[]>();for(const entity of entities){const key=groupValue(entity,dimension);grouped.set(key,[...(grouped.get(key)??[]),entity]);}const groups=[...grouped.entries()].sort(([a,av],[b,bv])=>bv.length-av.length||a.localeCompare(b)),clusterColumns=Math.max(1,Math.ceil(Math.sqrt(groups.length))),nodesPerRow=3,clusterWidth=570,maxRows=Math.max(1,...groups.map(([,items])=>Math.ceil(items.length/nodesPerRow))),clusterHeight=maxRows*145+110;const layout:GraphLayout={};groups.forEach(([,items],groupIndex)=>{const groupX=(groupIndex%clusterColumns)*clusterWidth,groupY=Math.floor(groupIndex/clusterColumns)*clusterHeight;items.sort((a,b)=>a.name.localeCompare(b.name)).forEach((entity,index)=>{layout[entity.id]=[groupX+(index%nodesPerRow)*180,groupY+70+Math.floor(index/nodesPerRow)*145]})});const values=Object.values(layout);if(values.length){const minX=Math.min(...values.map(([x])=>x)),maxX=Math.max(...values.map(([x])=>x)),minY=Math.min(...values.map(([,y])=>y)),maxY=Math.max(...values.map(([,y])=>y)),cx=(minX+maxX)/2,cy=(minY+maxY)/2;for(const id of Object.keys(layout)){layout[id]=[Math.round(layout[id]![0]-cx),Math.round(layout[id]![1]-cy)];}}return layout;}
