import type { Connection } from "./intelligence";
export const entitySources: Record<string,string> = {
thiel:"https://foundersfund.com/team/peter-thiel/",musk:"https://www.tesla.com/elon-musk",trump:"https://www.whitehouse.gov/administration/donald-j-trump/",altman:"https://forum.openai.com/public/videos/event-replay-sam-altman-on-building-the-future-of-ai-2026-04-06",openai:"https://openai.com/about/",palantir:"https://investors.palantir.com/news-events/news-releases",anduril:"https://www.anduril.com/news",cia:"https://www.cia.gov/about/",fbi:"https://www.fbi.gov/about",congress:"https://www.congress.gov/about",ccp:"https://english.www.gov.cn/news/topnews/202210/26/content_WS635921cdc6d0a757729e1cd4.html",anthropic:"https://www.anthropic.com/company",claude:"https://www.anthropic.com/news/introducing-claude",ai:"https://www.nist.gov/artificial-intelligence",agents:"https://www.anthropic.com/engineering/building-effective-agents"
};
const entries: [string,string,string,string,string,string][] = [
["thiel","palantir","Co-founder and chairman","Palantir's 2026 proxy identifies Peter Thiel as a co-founder and chairman. This records the role as stated in that filing.","https://www.sec.gov/Archives/edgar/data/1321655/000132165526000019/pltr-20260423.htm","2026-04-23"],
["musk","openai","Founding co-chair · historical","The 2015 launch announcement named Elon Musk as a co-chair. This is a historical affiliation, not a statement of a current role.","https://openai.com/index/introducing-openai/","2015-12-11"],
["altman","openai","Co-founder and CEO · 2026 profile","OpenAI's April 2026 event profile identifies Sam Altman as its co-founder and CEO.","https://forum.openai.com/public/videos/event-replay-sam-altman-on-building-the-future-of-ai-2026-04-06","2026-04-06"],
["openai","anduril","Announced partnership","Anduril announced a strategic partnership with OpenAI. This is a first-party announcement, not independent confirmation of a particular deployment.","https://www.anduril.com/news/anduril-partners-with-openai-to-advance-u-s-artificial-intelligence-leadership-and-protect-u-s","2024-12-04"],
["anduril","palantir","Army TITAN program partners","Anduril described its work with Palantir on the Army's TITAN program.","https://www.anduril.com/news/army-selects-anduril-and-palantir-to-deliver-titan","2024-03-07"],
["anthropic","claude","Introduced AI assistant","Anthropic introduced Claude as its AI assistant in March 2023.","https://www.anthropic.com/news/introducing-claude","2023-03-14"],
["claude","agents","Agent implementation example","Anthropic's engineering guide links to a computer-use agent reference implementation using Claude. This is a technical example, not a claim about autonomous capabilities in every setting.","https://www.anthropic.com/engineering/building-effective-agents","2024-12-19"],
["altman","congress","Testified before Senate subcommittee","The Senate Judiciary Committee lists Sam Altman as a witness at its May 2023 AI oversight hearing.","https://www.judiciary.senate.gov/committee-activity/hearings/oversight-of-ai-rules-for-artificial-intelligence","2023-05-16"],
["congress","fbi","Congressional oversight","The FBI explains that congressional committees review its activities. The source is undated; the displayed date is the date checked.","https://www.fbi.gov/about/faqs/who-monitors-or-oversees-the-fbi","2026-09-05"],
["cia","congress","Congressional liaison","CIA's organization page describes its congressional liaison function. The source is undated; the displayed date is the date checked.","https://www.cia.gov/about/organization/","2026-09-05"],
["congress","ccp","House select committee · 2023","The House agreed to H.Res.11 establishing a select committee on strategic competition with the Chinese Communist Party. This records the 2023 action.","https://www.congress.gov/bill/118th-congress/house-resolution/11","2023-01-10"],
["trump","ai","Signed AI export executive order","The July 23, 2025 executive order established an American AI exports program. This records the signed order without evaluating its effects.","https://www.whitehouse.gov/presidential-actions/2025/07/promoting-the-export-of-the-american-ai-technology-stack/","2025-07-23"],
["congress","ai","Held AI oversight hearing","The Senate Judiciary Subcommittee held an oversight hearing on artificial intelligence on May 16, 2023.","https://www.judiciary.senate.gov/committee-activity/hearings/oversight-of-ai-rules-for-artificial-intelligence","2023-05-16"],
["thiel","openai","Named launch donor · historical","OpenAI's 2015 launch announcement named Peter Thiel among its donors. It does not establish an individual donation amount or a current affiliation.","https://openai.com/index/introducing-openai/","2015-12-11"]
];
export const seedConnections: Connection[]=entries.map(([from,to,label,evidence,url,date],i)=>({id:"seed-"+i,from,to,label,evidence,url,date,status:"Documented"}));

