import {sqliteTable,text,integer,primaryKey,uniqueIndex,index} from "drizzle-orm/sqlite-core";
export const entities=sqliteTable("entities",{ownerId:text("owner_id").notNull(),id:text("id").notNull(),name:text("name").notNull(),nameKey:text("name_key").notNull(),kind:text("kind").notNull(),initials:text("initials").notNull(),description:text("description").notNull(),aliases:text("aliases").notNull(),followed:integer("followed").notNull().default(1),source:text("source").notNull(),color:text("color").notNull(),image:text("image").notNull().default(""),feedUrl:text("feed_url").notNull().default(""),lastCrawled:text("last_crawled").notNull().default(""),marketProfile:text("market_profile").notNull().default("{}")},t=>[primaryKey({columns:[t.ownerId,t.id]}),uniqueIndex("entities_owner_name").on(t.ownerId,t.nameKey),index("entities_owner_kind").on(t.ownerId,t.kind)]);
export const connections=sqliteTable("connections",{ownerId:text("owner_id").notNull(),id:text("id").notNull(),fromId:text("from_id").notNull(),toId:text("to_id").notNull(),label:text("label").notNull(),evidence:text("evidence").notNull(),url:text("url").notNull(),date:text("date").notNull(),status:text("status").notNull()},t=>[primaryKey({columns:[t.ownerId,t.id]})]);
export const briefings=sqliteTable("briefings",{ownerId:text("owner_id").notNull(),date:text("date").notNull(),content:text("content").notNull(),updated:text("updated").notNull()},t=>[primaryKey({columns:[t.ownerId,t.date]})]);
export const settings=sqliteTable("settings",{ownerId:text("owner_id").notNull(),key:text("key").notNull(),value:text("value").notNull()},t=>[primaryKey({columns:[t.ownerId,t.key]})]);

export const articles=sqliteTable("articles",{ownerId:text("owner_id").notNull(),id:text("id").notNull(),title:text("title").notNull(),url:text("url").notNull(),source:text("source").notNull(),summary:text("summary").notNull().default(""),published:text("published").notNull(),firstSeen:text("first_seen").notNull()},t=>[primaryKey({columns:[t.ownerId,t.id]}),index("articles_owner_published").on(t.ownerId,t.published)]);
export const articleEntities=sqliteTable("article_entities",{ownerId:text("owner_id").notNull(),articleId:text("article_id").notNull(),entityId:text("entity_id").notNull()},t=>[primaryKey({columns:[t.ownerId,t.articleId,t.entityId]}),index("article_entities_owner_entity").on(t.ownerId,t.entityId)]);
export const notes=sqliteTable("notes",{ownerId:text("owner_id").notNull(),id:text("id").notNull(),targetKind:text("target_kind").notNull(),targetId:text("target_id").notNull(),body:text("body").notNull(),created:text("created").notNull(),updated:text("updated").notNull()},t=>[primaryKey({columns:[t.ownerId,t.id]}),index("notes_owner_target").on(t.ownerId,t.targetKind,t.targetId)]);
export const boards=sqliteTable("boards",{ownerId:text("owner_id").notNull(),id:text("id").notNull(),name:text("name").notNull(),visibility:text("visibility").notNull().default("link"),proposalAudience:text("proposal_audience").notNull().default("none"),pattern:text("pattern").notNull().default("dots"),patternColor:text("pattern_color").notNull().default("#2e3c48"),surface:text("surface").notNull().default("#131d26"),gap:integer("gap").notNull().default(22),sort:integer("sort").notNull().default(0),image:text("image").notNull().default(""),imageFit:text("image_fit").notNull().default("cover"),nodeScale:integer("node_scale").notNull().default(100),created:text("created").notNull()},t=>[primaryKey({columns:[t.ownerId,t.id]}),index("boards_owner_sort").on(t.ownerId,t.sort)]);
export const boardNodes=sqliteTable("board_nodes",{ownerId:text("owner_id").notNull(),boardId:text("board_id").notNull(),entityId:text("entity_id").notNull(),x:integer("x").notNull(),y:integer("y").notNull()},t=>[primaryKey({columns:[t.ownerId,t.boardId,t.entityId]}),index("board_nodes_owner_board").on(t.ownerId,t.boardId)]);
export const shares=sqliteTable("shares",{token:text("token").primaryKey(),ownerId:text("owner_id").notNull(),boardId:text("board_id").notNull(),title:text("title").notNull(),created:text("created").notNull(),views:integer("views").notNull().default(0),lastViewed:text("last_viewed").notNull().default("")},t=>[index("shares_owner_board").on(t.ownerId,t.boardId)]);
export const entityAttributes=sqliteTable("entity_attributes",{ownerId:text("owner_id").notNull(),entityId:text("entity_id").notNull(),key:text("key").notNull(),value:text("value").notNull(),sourceUrl:text("source_url").notNull().default(""),origin:text("origin").notNull().default("owner"),contributor:text("contributor").notNull().default(""),updated:text("updated").notNull()},t=>[primaryKey({columns:[t.ownerId,t.entityId,t.key]}),index("entity_attributes_owner_key").on(t.ownerId,t.key)]);
export const profiles=sqliteTable("profiles",{ownerId:text("owner_id").primaryKey(),handle:text("handle").notNull(),displayName:text("display_name").notNull(),bio:text("bio").notNull().default(""),visibility:text("visibility").notNull().default("handle_only"),created:text("created").notNull()},t=>[uniqueIndex("profiles_handle").on(t.handle)]);
export const boardAccess=sqliteTable("board_access",{ownerId:text("owner_id").notNull(),boardId:text("board_id").notNull(),personId:text("person_id").notNull(),role:text("role").notNull(),added:text("added").notNull()},t=>[primaryKey({columns:[t.ownerId,t.boardId,t.personId]}),index("board_access_person").on(t.personId)]);
export const contributions=sqliteTable("contributions",{ownerId:text("owner_id").notNull(),id:text("id").notNull(),boardId:text("board_id").notNull(),kind:text("kind").notNull(),targetId:text("target_id").notNull().default(""),payload:text("payload").notNull(),evidenceUrl:text("evidence_url").notNull().default(""),message:text("message").notNull().default(""),contributor:text("contributor").notNull(),contributorLabel:text("contributor_label").notNull().default(""),status:text("status").notNull().default("pending"),created:text("created").notNull(),decided:text("decided").notNull().default("")},t=>[primaryKey({columns:[t.ownerId,t.id]}),index("contributions_owner_box").on(t.ownerId,t.boardId,t.kind,t.status,t.created)]);
export const connectionSources=sqliteTable("connection_sources",{ownerId:text("owner_id").notNull(),connectionId:text("connection_id").notNull(),url:text("url").notNull(),note:text("note").notNull().default(""),contributor:text("contributor").notNull().default(""),added:text("added").notNull()},t=>[primaryKey({columns:[t.ownerId,t.connectionId,t.url]})]);
