import {authenticatedUser,unauthorized} from "@/lib/access";
import {boardLayout,database,ensureBoards,getWorkspace,initialize,listBoards} from "@/lib/store";
import {kinds,safeWebUrl} from "@/lib/intelligence";
function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"private, no-store"}});}
export async function GET(request:Request){const owner=authenticatedUser(request);if(!owner)return unauthorized();try{const params=new URL(request.url).searchParams;if(params.has("boards")){await initialize(owner);return json({boards:await listBoards(owner)});}
if(params.has("layout")){await initialize(owner);await ensureBoards(owner);const db=database();const boardId=params.get("layout")??"";const board=boardId?await db.prepare("SELECT id FROM boards WHERE owner_id=? AND id=?").bind(owner,boardId).first():null;if(boardId&&!board)return json({error:"That board no longer exists."},404);const target=boardId||(await listBoards(owner))[0]?.id||"";const layout=target?await boardLayout(owner,target):{};const counts=await db.prepare("SELECT target_id AS id,count(*) AS total FROM notes WHERE owner_id=? AND target_kind='entity' GROUP BY target_id").bind(owner).all();return json({layout,noteCounts:Object.fromEntries(counts.results.map(item=>[item.id,Number(item.total)]))});}if(params.has("articles")){await initialize(owner);const db=database(),entityId=params.get("articles")??"";const exists=await db.prepare("SELECT id FROM entities WHERE owner_id=? AND id=?").bind(owner,entityId).first();if(!exists)return json({error:"Entity not found."},404);const requested=Number(params.get("limit")??50),limit=Number.isFinite(requested)?Math.max(1,Math.min(200,Math.trunc(requested))):50;const result=await db.prepare("SELECT a.id,a.title,a.url,a.source,a.summary,a.published,a.first_seen AS firstSeen FROM articles a JOIN article_entities ae ON ae.owner_id=a.owner_id AND ae.article_id=a.id WHERE a.owner_id=? AND ae.entity_id=? ORDER BY a.published DESC LIMIT ?").bind(owner,entityId,limit).all();return json({articles:result.results});}return json(await getWorkspace(owner))}catch(e){console.error("Workspace read failed",e);return json({error:"Saved data is temporarily unavailable. Please retry."},503)}}
export async function POST(request:Request){
const owner=authenticatedUser(request);if(!owner)return unauthorized();
const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return json({error:"Request origin is not allowed."},403);
if(!request.headers.get("content-type")?.includes("application/json"))return json({error:"JSON is required."},415);
let b:any;try{const raw=await request.text();if(raw.length>6000)return json({error:"Request is too large."},413);b=JSON.parse(raw);if(!b||typeof b!=="object"||Array.isArray(b))throw Error();}catch{return json({error:"Invalid request."},400)}
try{await initialize(owner);const db=database();
if(b.action==="layout"){if(!b.positions||typeof b.positions!=="object"||Array.isArray(b.positions))return json({error:"Layout positions are required."},400);const entries=Object.entries(b.positions as Record<string,unknown>);if(entries.length>100)return json({error:"A board supports up to 100 entities."},400);await ensureBoards(owner);const boardId=typeof b.boardId==="string"&&b.boardId?b.boardId:(await listBoards(owner))[0]?.id??"";const board=await db.prepare("SELECT id FROM boards WHERE owner_id=? AND id=?").bind(owner,boardId).first();if(!board)return json({error:"That board no longer exists."},404);const writes=[];for(const [id,value] of entries){if(!Array.isArray(value)||value.length!==2)continue;const x=Number(value[0]),y=Number(value[1]);if(!Number.isFinite(x)||!Number.isFinite(y))continue;writes.push(db.prepare("INSERT INTO board_nodes (owner_id,board_id,entity_id,x,y) VALUES (?,?,?,?,?) ON CONFLICT(owner_id,board_id,entity_id) DO UPDATE SET x=excluded.x,y=excluded.y").bind(owner,boardId,id,Math.round(x),Math.round(y)));}
if(writes.length)await db.batch(writes);return json({ok:true});}
if(b.action==="board-create"){const name=typeof b.name==="string"?b.name.trim():"";if(name.length<1||name.length>60)return json({error:"Name a board in 1–60 characters."},400);await ensureBoards(owner);const count=await db.prepare("SELECT count(*) AS total FROM boards WHERE owner_id=?").bind(owner).first<{total:number}>();if((count?.total??0)>=20)return json({error:"This workspace supports up to 20 boards."},400);const id=crypto.randomUUID();await db.prepare("INSERT INTO boards (owner_id,id,name,pattern,pattern_color,surface,gap,sort,created) VALUES (?,?,?,?,?,?,?,?,?)").bind(owner,id,name,"dots","#2e3c48","#131d26",22,count?.total??0,new Date().toISOString()).run();return json({ok:true,id},201);}
if(b.action==="board-update"){if(typeof b.id!=="string")return json({error:"Choose a board."},400);const board=await db.prepare("SELECT id FROM boards WHERE owner_id=? AND id=?").bind(owner,b.id).first();if(!board)return json({error:"That board no longer exists."},404);const sets=[],values=[];
if(b.name!==undefined){const name=typeof b.name==="string"?b.name.trim():"";if(name.length<1||name.length>60)return json({error:"Name a board in 1–60 characters."},400);sets.push("name=?");values.push(name);}
if(b.pattern!==undefined){if(!["dots","lines","cross","none"].includes(b.pattern))return json({error:"Choose a dot, line, cross, or plain background."},400);sets.push("pattern=?");values.push(b.pattern);}
if(b.patternColor!==undefined){if(typeof b.patternColor!=="string"||!/^#[0-9a-fA-F]{6}$/.test(b.patternColor))return json({error:"Enter a colour as a hex value like #2e3c48."},400);sets.push("pattern_color=?");values.push(b.patternColor);}
if(b.surface!==undefined){if(typeof b.surface!=="string"||!/^#[0-9a-fA-F]{6}$/.test(b.surface))return json({error:"Enter a colour as a hex value like #131d26."},400);sets.push("surface=?");values.push(b.surface);}
if(b.gap!==undefined){const gap=Number(b.gap);if(!Number.isFinite(gap)||gap<8||gap>80)return json({error:"Choose a spacing between 8 and 80."},400);sets.push("gap=?");values.push(Math.round(gap));}
if(!sets.length)return json({error:"Nothing to change."},400);await db.prepare("UPDATE boards SET "+sets.join(",")+" WHERE owner_id=? AND id=?").bind(...values,owner,b.id).run();return json({ok:true});}
if(b.action==="board-delete"){if(typeof b.id!=="string")return json({error:"Choose a board."},400);const total=await db.prepare("SELECT count(*) AS total FROM boards WHERE owner_id=?").bind(owner).first<{total:number}>();if((total?.total??0)<=1)return json({error:"Keep at least one board."},400);const result=await db.prepare("DELETE FROM boards WHERE owner_id=? AND id=?").bind(owner,b.id).run();if(!result.meta.changes)return json({error:"That board no longer exists."},404);await db.prepare("DELETE FROM board_nodes WHERE owner_id=? AND board_id=?").bind(owner,b.id).run();return json({ok:true});}
if(b.action==="board-place"){if(typeof b.id!=="string"||typeof b.entityId!=="string")return json({error:"Choose a board and an entity."},400);const board=await db.prepare("SELECT id FROM boards WHERE owner_id=? AND id=?").bind(owner,b.id).first();if(!board)return json({error:"That board no longer exists."},404);const entity=await db.prepare("SELECT id FROM entities WHERE owner_id=? AND id=?").bind(owner,b.entityId).first();if(!entity)return json({error:"Entity not found."},404);const count=await db.prepare("SELECT count(*) AS total FROM board_nodes WHERE owner_id=? AND board_id=?").bind(owner,b.id).first<{total:number}>();if((count?.total??0)>=100)return json({error:"A board supports up to 100 entities."},400);const at=Array.isArray(b.position)&&b.position.length===2?b.position as [number,number]:[0,0];await db.prepare("INSERT OR IGNORE INTO board_nodes (owner_id,board_id,entity_id,x,y) VALUES (?,?,?,?,?)").bind(owner,b.id,b.entityId,Math.round(Number(at[0])||0),Math.round(Number(at[1])||0)).run();return json({ok:true});}
if(b.action==="board-remove"){if(typeof b.id!=="string"||typeof b.entityId!=="string")return json({error:"Choose a board and an entity."},400);await db.prepare("DELETE FROM board_nodes WHERE owner_id=? AND board_id=? AND entity_id=?").bind(owner,b.id,b.entityId).run();return json({ok:true});}
if(b.action==="feed"){const feedUrl=b.feedUrl===""?"":safeWebUrl(b.feedUrl);if(typeof b.id!=="string"||typeof b.feedUrl!=="string"||(b.feedUrl!==""&&!feedUrl))return json({error:"Choose an entity and enter a valid feed URL, or leave it empty for news search."},400);const result=await db.prepare("UPDATE entities SET feed_url=?,last_crawled='' WHERE owner_id=? AND id=?").bind(feedUrl,owner,b.id).run();return result.meta.changes?json({ok:true}):json({error:"Entity not found."},404);}
if(b.action==="follow"){if(typeof b.id!=="string"||typeof b.followed!=="boolean")return json({error:"A valid entity and follow state are required."},400);const exists=await db.prepare("SELECT id FROM entities WHERE owner_id=? AND id=?").bind(owner,b.id).first();if(!exists)return json({error:"Entity not found."},404);await db.prepare("UPDATE entities SET followed=? WHERE owner_id=? AND id=?").bind(b.followed?1:0,owner,b.id).run();return json({ok:true});}
if(b.action==="add"){const name=typeof b.name==="string"?b.name.trim():"";const source=safeWebUrl(b.source);if(name.length<2||name.length>100||!kinds.includes(b.kind)||!source)return json({error:"Enter a name (2–100 characters), a category, and a public source URL."},400);
const feedUrl=b.feedUrl===undefined||b.feedUrl===""?"":safeWebUrl(b.feedUrl);if(b.feedUrl!==undefined&&(typeof b.feedUrl!=="string"||(b.feedUrl!==""&&!feedUrl)))return json({error:"Enter a valid feed URL, or leave it empty for news search."},400);
const count=await db.prepare("SELECT count(*) AS total FROM entities WHERE owner_id=?").bind(owner).first<{total:number}>();if((count?.total??0)>=100)return json({error:"This workspace supports up to 100 entities."},400);
const exists=await db.prepare("SELECT id FROM entities WHERE owner_id=? AND name_key=?").bind(owner,name.toLowerCase()).first();if(exists)return json({error:"That entity is already in your workspace."},409);
const id=crypto.randomUUID();const initials=name.split(/\s+/).slice(0,2).map((s:string)=>s[0]).join("").toUpperCase();const color=b.kind==="Person"?"#ed997b":b.kind==="Company"?"#86a8fc":b.kind==="Government"?"#c2acf0":"#78c7af";
await db.batch([db.prepare("INSERT INTO entities (owner_id,id,name,name_key,kind,initials,description,aliases,followed,source,color,feed_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(owner,id,name,name.toLowerCase(),b.kind,initials,"Added to your personal watchlist.",JSON.stringify([name]),1,source,color,feedUrl),db.prepare("INSERT OR IGNORE INTO article_entities (owner_id,article_id,entity_id) SELECT ?,id,? FROM articles WHERE owner_id=? AND lower(title) LIKE ? ESCAPE '\\'").bind(owner,id,owner,"%"+name.toLowerCase().replace(/[\\%_]/g,(c:string)=>"\\"+c)+"%")]);return json({ok:true,id},201);}
if(b.action==="connect"){const from=typeof b.from==="string"?b.from:"",to=typeof b.to==="string"?b.to:"",label=typeof b.label==="string"?b.label.trim():"",evidence=typeof b.evidence==="string"?b.evidence.trim():"",url=safeWebUrl(b.url);if(!from||!to||from===to||!label||label.length>100||!evidence||evidence.length>1200||!url||!["Documented","Hypothesis"].includes(b.status)||!/^\d{4}-\d{2}-\d{2}$/.test(b.date??"")||Number.isNaN(Date.parse(b.date))||new Date(b.date).toISOString().slice(0,10)!==b.date||b.date>new Date().toISOString().slice(0,10))return json({error:"Choose two different entities and provide evidence, a valid source URL, and a source date no later than today."},400);
const nodes=await db.prepare("SELECT id FROM entities WHERE owner_id=? AND id IN (?,?)").bind(owner,from,to).all();if(nodes.results.length!==2)return json({error:"Both entities must exist."},400);const id=crypto.randomUUID();await db.prepare("INSERT INTO connections (owner_id,id,from_id,to_id,label,evidence,url,date,status) VALUES (?,?,?,?,?,?,?,?,?)").bind(owner,id,from,to,label,evidence,url,b.date,b.status).run();return json({ok:true,id},201);}
return json({error:"Unknown action."},400);
}catch(e){console.error("Workspace update failed",e);return json({error:"The change could not be saved. Please retry."},503)}
}
